Sync bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -28,7 +28,7 @@ trigger_map:
 - push_branch: master
   workflow: test
 - pull_request_source_branch: '*'
-  workflow: test
+  workflow: PR-Test
 workflows:
   _prepare:
     steps:
@@ -61,47 +61,41 @@ workflows:
               bundle exec fastlane upload_build_cache
             fi
         title: Install dependencies
-  deploy:
+  PR-Test:
+    before_run:
+    - _prepare
     steps:
-    - activate-ssh-key@4.0.3:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4.0.14: {}
-    - cache-pull@2.0.1: {}
     - script@1.1.5:
-        title: Do anything with Script step
-    - certificate-and-profile-installer@1.10.1: {}
-    - cocoapods-install@1.7.2: {}
-    - xcode-test@2.3.2:
         inputs:
-        - project_path: $BITRISE_PROJECT_PATH
-        - scheme: $BITRISE_SCHEME
-    - xcode-archive@2.5.0:
-        inputs:
-        - project_path: $BITRISE_PROJECT_PATH
-        - scheme: $BITRISE_SCHEME
-        - export_method: $BITRISE_EXPORT_METHOD
-    - deploy-to-bitrise-io@1.6.0: {}
-    - cache-push@2.2.0: {}
-  nightly-build: {}
-  primary:
-    steps:
-    - activate-ssh-key@4.0.3:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4.0.14: {}
-    - cache-pull@2.0.1: {}
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -ex
+            bundle exec fastlane run danger
+        title: Danger
     - script@1.1.5:
-        title: Do anything with Script step
-    - certificate-and-profile-installer@1.10.1: {}
-    - cocoapods-install@1.7.2: {}
-    - carthage@3.2.1: {}
-    - cache-push@2.2.0:
         inputs:
-        - cache_paths: $BITRISE_CACHE_DIR
-    - xcode-test@2.3.2:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -ex
+            bundle exec fastlane duiet_tests
+        title: Test
+    - cache-push@2.2.1: {}
+    - deploy-to-bitrise-io@1.9.2:
         inputs:
-        - project_path: $BITRISE_PROJECT_PATH
-        - scheme: $BITRISE_SCHEME
-    - deploy-to-bitrise-io@1.6.0: {}
+        - is_enable_public_page: "false"
+    - slack@3.1.3:
+        inputs:
+        - api_token: $SLACK_API_TOKEN
+        - channel: '#duiet_ci'
+        - pretext: '*Test Succeeded!*'
+        - channel_on_error: '#duiet_ci'
+        - emoji_on_error: ""
+        - text: ""
+        - text_on_error: $BITRISE_GIT_MESSAGE
+        - pretext_on_error: '*Test Failed!*'
+        - webhook_url: $SLACK_WEBHOOK_URL
   sync-bitrise-yml:
     before_run:
     - _prepare
